/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Breadcrumb: typeof import("./src/components/Breadcrumb/index.vue")["default"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    Hamburger: typeof import("./src/components/Hamburger/index.vue")["default"];
    IconSelect: typeof import("./src/components/IconSelect/index.vue")["default"];
    LangSelect: typeof import("./src/components/LangSelect/index.vue")["default"];
    Pagination: typeof import("./src/components/Pagination/index.vue")["default"];
    RightPanel: typeof import("./src/components/RightPanel/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Screenfull: typeof import("./src/components/Screenfull/index.vue")["default"];
    SizeSelect: typeof import("./src/components/SizeSelect/index.vue")["default"];
    SvgIcon: typeof import("./src/components/SvgIcon/index.vue")["default"];
  }
}
